@startuml
title 'Diagramme de classes'

package model #DDFFDD {
  class Event {
  + id : long
  + date : Date
  + valeur: double
  + commentaire: String
  --

  }

  class TimeSerie {
  + serieId: Uuid
  + listEvents: Arraylist
  + titre: String
  + description: String
  + owner: Uuid
  + readers: Arraylist<Uuid>
  + editors: Arraylist<Uuid>
  --
  + void addEvent(Event event)
  + void updateEvent(Event event)
  + void deleteEvent(Event event)
  }

  class User {
  + userId: Uuid
  + Name: String
  --
  + TimeSerie createSerie()
  + TimeSerie deleteSerie(Uuid serieId)
  + void updateSerieTitle(long serieId, String newTitle)
  + void updateSerieDescription(long serieId, String newDescription)
  + void addEventToSerie(Event event, TimeSerie serie)
  + void deleteEventFromSerie(Event event, TimeSerie serie)
  + void updateEventFromSerie(Event event, TimeSerie serie)
  + void addEditor(Uuid userId)
  + void addReader(Uuid userId)
  + void deleteEditor(Uuid userId)
  + void deleteReader(Uuid userId)
  }

  class Tag {
  + name: String
  }
}

package service #DD0623 {
  class EventService {
  + id : long
  + date : Date
  + valeur: double
  + commentaire: String
  --

  }

  class TimeSerieService {
  + serieId: Uuid
  + listEvents: Arraylist
  + titre: String
  + description: String
  + owner: Uuid
  + readers: Arraylist<Uuid>
  + editors: Arraylist<Uuid>
  --
  + void addEvent(Event event)
  + void updateEvent(Event event)
  + void deleteEvent(Event event)
  }

  class UserService {
  + userId: Uuid
  + Name: String
  --
  + TimeSerie createSerie()
  + TimeSerie deleteSerie(Uuid serieId)
  + void updateSerieTitle(long serieId, String newTitle)
  + void updateSerieDescription(long serieId, String newDescription)
  + void addEventToSerie(Event event, TimeSerie serie)
  + void deleteEventFromSerie(Event event, TimeSerie serie)
  + void updateEventFromSerie(Event event, TimeSerie serie)
  + void addEditor(Uuid userId)
  + void addReader(Uuid userId)
  + void deleteEditor(Uuid userId)
  + void deleteReader(Uuid userId)
  }

  class TagService {
  + name: String
  }
}

TimeSerie -right- "*" Event
User -up-> TimeSerie : instanciate
Event -- "*" Tag
@enduml